name: Code Analysis and Secret Detection

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Étape : Détection de secrets avec Gitleaks
      - name: Set up Gitleaks
        run: |
          curl -L https://github.com/gitleaks/gitleaks/releases/download/v8.22.1/gitleaks_8.22.1_linux_x64.tar.gz -o gitleaks.tar.gz
          tar -xvf gitleaks.tar.gz
          chmod +x gitleaks
          ./gitleaks --version  # Vérification de la version

      - name: Run Gitleaks to check for secrets
        run: |
          ./gitleaks --repo="." --report="gitleaks-report.json" --verbose

      # Téléchargement des rapports
      - name: Upload Gitleaks report
        uses: actions/upload-artifact@v3
        with:
          name: gitleaks-report
          path: gitleaks-report.json
