name: Code Analysis and Secret Detection

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Étape 1 : Exécution de PMD pour détecter les code smells et problèmes de style
      - name: Run PMD analysis
        run: |
          curl -s https://github.com/pmd/pmd/releases/download/pmd_releases/pmd-bin-6.43.0.zip -o pmd.zip
          unzip pmd.zip -d pmd
          ./pmd/bin/run.sh pmd -d . -R rulesets/java/quickstart.xml -f text > pmd-report.txt
        continue-on-error: true # Permet de continuer même si PMD détecte des problèmes

      # Étape 2 : Détection de secrets avec Gitleaks
      - name: Set up Gitleaks
        run: |
          curl -L https://github.com/gitleaks/gitleaks/releases/download/v8.22.1/gitleaks_8.22.1_linux_x64.tar.gz -o gitleaks.tar.gz
          tar -xvf gitleaks.tar.gz
          chmod +x gitleaks  # Changer les permissions pour rendre gitleaks exécutable
          mv gitleaks /usr/local/bin/gitleaks

      - name: Run Gitleaks to check for secrets
        run: |
          gitleaks --version
          gitleaks --path="." --report="gitleaks-report.json" --verbose

      # Étape 3 : Téléchargement des rapports PMD et Gitleaks
      - name: Upload PMD report
        uses: actions/upload-artifact@v3
        with:
          name: pmd-report
          path: pmd-report.txt

      - name: Upload Gitleaks report
        uses: actions/upload-artifact@v3
        with:
          name: gitleaks-report
          path: gitleaks-report.json
