name: Release Automation

permissions:
  contents: write

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'oracle'

      - name: Build project and run tests
        run: |
          ./gradlew build test  


      - name: Generate changelog
        id: changelog
        run: |
          
          LAST_TAG=$(git describe --tags --abbrev=0)
          echo "Last tag: $LAST_TAG"
          CHANGES=$(git log $LAST_TAG..HEAD --oneline)
          echo "Changelog: $CHANGES"
          echo "::set-output name=changelog::$CHANGES"


      - name: Create GitHub release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            build/libs/*.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true

      - name: Publish changelog in release message
        run: |
          gh release create $GITHUB_REF --title "Release $GITHUB_REF" --notes "${{ steps.changelog.outputs.changelog }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
