name: Build and Test Backend

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        java-version: [17, 20] # Les versions de Java à tester

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java-version }}
          distribution: temurin

      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: gradle-${{ runner.os }}-${{ matrix.java-version }}
          restore-keys: |
            gradle-${{ runner.os }}-

      - name: Build and test
        run: ./gradlew clean build



      - name: Run Checkstyle
        run: ./gradlew checkstyleMain checkstyleTest


      - name: Run SonarCloud Analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          ./gradlew sonarqube \
            -Dsonar.projectKey=your_project_key \
            -Dsonar.organization=your_organization \
            -Dsonar.host.url=https://sonarcloud.io


      - name: Check for secrets with GitLeaks
        uses: zricethezav/gitleaks-action@v2
        with:
          args: --path=. --report-format=json --report-path=gitleaks-report.json
